#!/usr/bin/env bash
set -euo pipefail
HOME_COLMAP="$HOME/workspaceCpp/colmap/build/src/colmap/exe"
echo $HOME_COLMAP
ls $HOME_COLMAP

$HOME_COLMAP/colmap patch_match_stereo \
  --workspace_path /data/BG/dense \
  --workspace_format COLMAP
  
  
